/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  ButtonInterface,
} from './components/simple-paragraph/button.interface';


export namespace Components {

  interface SimpleParagraph2 {
    /**
    * Buttons
    */
    'buttons': ButtonInterface[];
    /**
    * Center
    */
    'center': boolean;
    /**
    * Header for the component
    */
    'header': string;
    /**
    * Message for the component
    */
    'message': string;
    /**
    * Mode (styles)
    */
    'mode': string;
    /**
    * Type
    */
    'type': string;
    /**
    * Width
    */
    'width': string;
  }
  interface SimpleParagraph2Attributes extends StencilHTMLAttributes {
    /**
    * Buttons
    */
    'buttons'?: ButtonInterface[];
    /**
    * Center
    */
    'center'?: boolean;
    /**
    * Header for the component
    */
    'header'?: string;
    /**
    * Message for the component
    */
    'message'?: string;
    /**
    * Mode (styles)
    */
    'mode'?: string;
    /**
    * Type
    */
    'type'?: string;
    /**
    * Width
    */
    'width'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'SimpleParagraph2': Components.SimpleParagraph2;
  }

  interface StencilIntrinsicElements {
    'simple-paragraph2': Components.SimpleParagraph2Attributes;
  }


  interface HTMLSimpleParagraph2Element extends Components.SimpleParagraph2, HTMLStencilElement {}
  var HTMLSimpleParagraph2Element: {
    prototype: HTMLSimpleParagraph2Element;
    new (): HTMLSimpleParagraph2Element;
  };

  interface HTMLElementTagNameMap {
    'simple-paragraph2': HTMLSimpleParagraph2Element
  }

  interface ElementTagNameMap {
    'simple-paragraph2': HTMLSimpleParagraph2Element;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
