/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface SimpleParagraph {
    /**
    * Message for the component
    */
    'message': string;
    /**
    * Mode (styles)
    */
    'mode': string;
    /**
    * Width
    */
    'width': string;
  }
  interface SimpleParagraphAttributes extends StencilHTMLAttributes {
    /**
    * Message for the component
    */
    'message'?: string;
    /**
    * Mode (styles)
    */
    'mode'?: string;
    /**
    * Width
    */
    'width'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'SimpleParagraph': Components.SimpleParagraph;
  }

  interface StencilIntrinsicElements {
    'simple-paragraph': Components.SimpleParagraphAttributes;
  }


  interface HTMLSimpleParagraphElement extends Components.SimpleParagraph, HTMLStencilElement {}
  var HTMLSimpleParagraphElement: {
    prototype: HTMLSimpleParagraphElement;
    new (): HTMLSimpleParagraphElement;
  };

  interface HTMLElementTagNameMap {
    'simple-paragraph': HTMLSimpleParagraphElement
  }

  interface ElementTagNameMap {
    'simple-paragraph': HTMLSimpleParagraphElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
